# %% [markdown]
# # 03 — Analysis
#
# Analyze experiment results and generate publication-ready figures for experiments
# E1–E5.
#
# **Paper sections**:
# - §4.1 E1 — Overall Segmentation Quality (Simple EN Baseline)
# - §4.2 E2 — Cross-Language Comparison (EN vs PT)
# - §4.3 E3 — Prompt Formulation Impact (Type × Language)
# - §4.4 E4 — Grounding vs Segmentation Diagnosis
# - §4.5 E5 — Failure Taxonomy
#
# All CSVs are loaded from `results/tables/`, which are generated by notebook 02.

# %%
import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

from vlm_pipeline.visualization import generate_all_figures

%matplotlib inline
sns.set_theme(style="whitegrid", context="notebook")

TABLES_DIR = Path("../results/tables")
FIGURES_DIR = Path("../results/figures")
RAW_DIR = Path("../results/raw")

def _load_csv(name: str) -> pd.DataFrame | None:
    """Load a CSV from the tables directory with an existence check."""
    path = TABLES_DIR / name
    if path.exists():
        return pd.read_csv(path)
    print(f"⚠️  {name} not found at {path}. Run notebook 02 first.")
    return None

# %% [markdown]
# ## E1 — Overall Quality (Simple EN Baseline)
#
# Per-class mean Mask IoU for the simple English prompt baseline. This establishes
# the reference performance before examining language and prompt effects.

# %%
e1 = _load_csv("e1_overall.csv")
if e1 is not None:
    display(e1.style.format(precision=3).background_gradient(
        subset=[c for c in e1.columns if e1[c].dtype == "float64"],
        cmap="YlOrRd",
    ))

    # Bar chart
    ordered = e1.sort_values("mean_mask_iou", ascending=False)
    fig, ax = plt.subplots(figsize=(10, 5))
    sns.barplot(data=ordered, x="class_name", y="mean_mask_iou", palette="colorblind", ax=ax)
    ax.set_xlabel("Class")
    ax.set_ylabel("Mean Mask IoU")
    ax.set_title("E1: Per-Class mIoU (Simple EN Baseline)")
    ax.set_ylim(0, 1)
    plt.xticks(rotation=45, ha="right")
    plt.tight_layout()
    plt.show()

# %% [markdown]
# ## E1 — Utility Distribution
#
# Stacked bar chart showing the percentage of instances classified as *good*
# (IoU ≥ 0.75), *correctable* (0.50 ≤ IoU < 0.75), or *bad* (IoU < 0.50).

# %%
e1_util = _load_csv("e1_utility_distribution.csv")
if e1_util is not None:
    display(e1_util)

    util_cols = [c for c in ("pct_good", "pct_correctable", "pct_bad") if c in e1_util.columns]
    if util_cols:
        fig, ax = plt.subplots(figsize=(10, 5))
        e1_util_sorted = e1_util.sort_values(util_cols[0], ascending=False)
        bottom = np.zeros(len(e1_util_sorted))
        colors = {"pct_good": "#55a868", "pct_correctable": "#c44e52", "pct_bad": "#8c8c8c"}
        labels = {"pct_good": "Good (≥0.75)", "pct_correctable": "Correctable (0.50–0.75)", "pct_bad": "Bad (<0.50)"}
        x = np.arange(len(e1_util_sorted))
        for col in util_cols:
            vals = e1_util_sorted[col].values
            ax.bar(x, vals, bottom=bottom, label=labels.get(col, col), color=colors.get(col, None))
            bottom += vals
        ax.set_xticks(x)
        ax.set_xticklabels(e1_util_sorted["class_name"], rotation=45, ha="right")
        ax.set_ylabel("Percentage (%)")
        ax.set_title("E1: Utility Distribution per Class")
        ax.legend(loc="upper right")
        plt.tight_layout()
        plt.show()

# %% [markdown]
# ## E2 — Language Comparison (EN vs PT)
#
# Heatmap showing mean Mask IoU for each class × language combination. This
# reveals which classes are sensitive to prompt language.

# %%
e2 = _load_csv("e2_lang_comparison.csv")
if e2 is not None:
    display(e2.style.format(precision=3))

    pivot = e2.pivot_table(index="class_name", columns="language", values="mean_mask_iou")
    fig, ax = plt.subplots(figsize=(6, 8))
    sns.heatmap(pivot, annot=True, fmt=".3f", cmap="YlOrRd",
                vmin=0, vmax=1, linewidths=0.5, ax=ax)
    ax.set_title("E2: mIoU by Class × Language")
    ax.set_ylabel("Class")
    ax.set_xlabel("Language")
    plt.tight_layout()
    plt.show()

# %% [markdown]
# ## E2 — Language Delta
#
# Per-class difference in mIoU between English and Portuguese prompts.
# Positive values mean English outperforms Portuguese.

# %%
e2_delta = _load_csv("e2_lang_delta.csv")
if e2_delta is not None:
    display(e2_delta.style.format(precision=4))

    delta_col = [c for c in e2_delta.columns if "delta" in c.lower() or "diff" in c.lower()]
    if not delta_col:
        # Fallback: compute from the main data if delta column not explicit
        delta_col = [c for c in e2_delta.columns if e2_delta[c].dtype == "float64"]
    if delta_col:
        col = delta_col[0]
        sorted_delta = e2_delta.sort_values(col, ascending=True)
        fig, ax = plt.subplots(figsize=(10, 5))
        colors = ["#4c72b0" if v >= 0 else "#dd8452" for v in sorted_delta[col]]
        bars = ax.barh(sorted_delta["class_name"], sorted_delta[col], color=colors)
        ax.set_xlabel(f"{col} (EN − PT)")
        ax.set_title("E2: Language Delta per Class")
        ax.axvline(x=0, color="grey", linewidth=0.8, linestyle="--")
        # Annotate bars with values
        for bar, val in zip(bars, sorted_delta[col]):
            offset = 0.005 if val >= 0 else -0.005
            ha = "left" if val >= 0 else "right"
            ax.text(val + offset, bar.get_y() + bar.get_height() / 2,
                    f"{val:+.3f}", va="center", ha=ha, fontsize=8)
        plt.tight_layout()
        plt.show()

# %% [markdown]
# ## E3 — Prompt Formulation Impact (Primary: EN)
#
# In the primary experiment (EN-only), this chart compares prompt types directly.
# If appendix language data is present, the language-interaction table is shown
# separately below.

# %%
e3 = _load_csv("e3_prompt_type.csv")
if e3 is not None:
    display(e3.style.format(precision=3))

    fig, ax = plt.subplots(figsize=(10, 5))
    if "language" in e3.columns:
        sns.barplot(data=e3, x="prompt_type", y="mean_mask_iou",
                    hue="language", palette="colorblind", ax=ax)
        ax.legend(title="Language")
    else:
        sns.barplot(data=e3, x="prompt_type", y="mean_mask_iou",
                    palette="colorblind", ax=ax)
    ax.set_xlabel("Prompt Type")
    ax.set_ylabel("Mean Mask IoU")
    ax.set_title("E3: Prompt Formulation Impact")
    ax.set_ylim(0, 1)
    plt.tight_layout()
    plt.show()

# %% [markdown]
# ## E3 — Inferential Statistics (Kruskal-Wallis + Dunn-Holm)
#
# Non-parametric comparison across prompt types, with pairwise post-hoc tests
# corrected by Holm-Bonferroni.

# %%
e3_stats = _load_csv("e3_prompt_stats.csv")
e3_pairwise = _load_csv("e3_prompt_pairwise_dunn.csv")

if e3_stats is not None:
    display(e3_stats.style.format(precision=6))

if e3_pairwise is not None:
    display(e3_pairwise.style.format(precision=6))

# %% [markdown]
# ## E3 (Appendix) — Prompt Type × Language
#
# Optional appendix table generated only when both EN and PT are present.

# %%
e3_appendix = _load_csv("e3_prompt_lang_appendix.csv")
if e3_appendix is not None:
    display(e3_appendix.style.format(precision=3))

    fig, ax = plt.subplots(figsize=(10, 5))
    sns.barplot(data=e3_appendix, x="prompt_type", y="mean_mask_iou",
                hue="language", palette="colorblind", ax=ax)
    ax.set_xlabel("Prompt Type")
    ax.set_ylabel("Mean Mask IoU")
    ax.set_title("E3 Appendix: Prompt Type × Language")
    ax.set_ylim(0, 1)
    ax.legend(title="Language")
    plt.tight_layout()
    plt.show()

# %% [markdown]
# ## E3 — Best prompt per class
#
# For each of the 10 classes, identify which prompt_type × language combination
# yields the highest mean Mask IoU.

# %%
if e3 is not None and "class_name" in e3.columns:
    best_per_class = (
        e3.loc[e3.groupby("class_name")["mean_mask_iou"].idxmax()]
        .sort_values("mean_mask_iou", ascending=False)
        [["class_name", "language", "prompt_type", "mean_mask_iou"]]
        .reset_index(drop=True)
    )
    print("Best prompt configuration per class:")
    display(best_per_class)
elif e3 is not None:
    # Aggregate view — best prompt type overall
    best = e3.groupby(["language", "prompt_type"])["mean_mask_iou"].mean().reset_index()
    best = best.sort_values("mean_mask_iou", ascending=False)
    print("Best overall prompt configurations:")
    display(best)

# %% [markdown]
# ## E4 — Grounding vs Segmentation Diagnosis
#
# Conditional analysis: given a correct grounding (box IoU ≥ threshold), how
# accurate is the segmentation? This isolates SAM 2.1's contribution from
# Grounding DINO's.

# %%
e4 = _load_csv("e4_conditional.csv")
if e4 is not None:
    display(e4.style.format(precision=3))

    # Commentary
    if "conditional_mask_iou" in e4.columns:
        overall_mask = e4["mean_mask_iou"].mean() if "mean_mask_iou" in e4.columns else None
        cond_mask = e4["conditional_mask_iou"].mean()
        if overall_mask is not None:
            gap = cond_mask - overall_mask
            print(f"\nConditional mIoU (given correct grounding): {cond_mask:.3f}")
            print(f"Overall mIoU:                                {overall_mask:.3f}")
            print(f"Gap (segmentation headroom):                 {gap:+.3f}")

# %% [markdown]
# ## E4 — Error Source Analysis
#
# Pie chart showing the breakdown of errors by source: grounding failures
# (missed or wrong box) vs segmentation failures (correct box, poor mask).

# %%
e4_error = _load_csv("e4_error_source.csv")
if e4_error is not None:
    display(e4_error)

    count_col = [c for c in e4_error.columns if "count" in c.lower() or "pct" in c.lower()]
    label_col = [c for c in e4_error.columns if "source" in c.lower() or "type" in c.lower()]
    if count_col and label_col:
        fig, ax = plt.subplots(figsize=(7, 7))
        ax.pie(
            e4_error[count_col[0]],
            labels=e4_error[label_col[0]],
            autopct="%1.1f%%",
            startangle=140,
            colors=sns.color_palette("colorblind", len(e4_error)),
        )
        ax.set_title("E4: Error Source Breakdown")
        plt.tight_layout()
        plt.show()

# %% [markdown]
# ## E4 — Box IoU vs Mask IoU Scatter
#
# Each point is a matched prediction instance. Points above the diagonal indicate
# segmentation quality exceeds grounding quality; below means the opposite.

# %%
# Build scatter data from raw per-image JSON files
records = []
if RAW_DIR.exists():
    for jf in sorted(RAW_DIR.glob("*.json")):
        data = json.loads(jf.read_text(encoding="utf-8"))
        for r in data.get("results", []):
            if "box_iou" in r and "mask_iou" in r:
                records.append({
                    "box_iou": r["box_iou"],
                    "mask_iou": r["mask_iou"],
                    "language": r.get("language", "unknown"),
                })

if records:
    scatter_df = pd.DataFrame(records)
    fig, ax = plt.subplots(figsize=(7, 7))
    sns.scatterplot(data=scatter_df, x="box_iou", y="mask_iou",
                    hue="language", alpha=0.4, s=15, palette="colorblind", ax=ax)
    ax.plot([0, 1], [0, 1], ls="--", color="grey", linewidth=0.8, label="y=x")
    ax.set_xlabel("Box IoU (Grounding)")
    ax.set_ylabel("Mask IoU (Segmentation)")
    ax.set_title("E4: Box IoU vs Mask IoU")
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.legend(title="Language")
    plt.tight_layout()
    plt.show()

    print(f"Total scatter points: {len(scatter_df):,}")
    print(f"Points above diagonal (mask > box): {(scatter_df['mask_iou'] > scatter_df['box_iou']).sum():,}")
    print(f"Points below diagonal (box > mask): {(scatter_df['mask_iou'] < scatter_df['box_iou']).sum():,}")
else:
    print("⚠️  No raw result files found — run notebook 02 first.")

# %% [markdown]
# ## E5 — Failure Taxonomy
#
# Categorization of failure cases: false positives, missed detections,
# low-IoU matches, and boundary errors.

# %%
e5 = _load_csv("e5_failure_taxonomy.csv")
if e5 is not None:
    display(e5)

    fig, ax = plt.subplots(figsize=(8, 4))
    ordered = e5.sort_values("count", ascending=True)
    sns.barplot(data=ordered, x="count", y="failure_type",
                orient="h", palette="colorblind", ax=ax)
    ax.set_xlabel("Count")
    ax.set_ylabel("Failure Type")
    ax.set_title("E5: Failure Taxonomy Distribution")
    plt.tight_layout()
    plt.show()

    # Show percentage breakdown
    total_failures = e5["count"].sum()
    if total_failures > 0:
        e5_pct = e5.copy()
        e5_pct["pct"] = (e5_pct["count"] / total_failures * 100).round(1)
        print(f"\nTotal failures: {total_failures:,}")
        display(e5_pct)

# %% [markdown]
# ## Generate all publication figures
#
# Write high-resolution figures to `results/figures/` for inclusion in the paper.

# %%
if TABLES_DIR.exists():
    generate_all_figures(str(TABLES_DIR), str(FIGURES_DIR))
    generated = sorted(FIGURES_DIR.glob("*.png")) if FIGURES_DIR.exists() else []
    print(f"Generated {len(generated)} figures in {FIGURES_DIR}/:")
    for f in generated:
        print(f"  {f.name}")
else:
    print("⚠️  Tables directory not found — run notebook 02 first.")

# %% [markdown]
# ## Key findings summary
#
# Automated extraction of headline results for the paper abstract and conclusion.

# %%
print("=" * 60)
print("KEY FINDINGS SUMMARY")
print("=" * 60)

# Best and worst class (E1)
if e1 is not None:
    best_class = e1.loc[e1["mean_mask_iou"].idxmax()]
    worst_class = e1.loc[e1["mean_mask_iou"].idxmin()]
    print(f"\n  Best class:   {best_class['class_name']} "
          f"(mIoU = {best_class['mean_mask_iou']:.3f})")
    print(f"  Worst class:  {worst_class['class_name']} "
          f"(mIoU = {worst_class['mean_mask_iou']:.3f})")
    print(f"  Overall mean: {e1['mean_mask_iou'].mean():.3f}")

# Language effect (E2)
if e2 is not None and "language" in e2.columns:
    lang_means = e2.groupby("language")["mean_mask_iou"].mean()
    if "en" in lang_means.index and "pt" in lang_means.index:
        effect = lang_means["en"] - lang_means["pt"]
        print(f"\n  EN mean mIoU: {lang_means['en']:.3f}")
        print(f"  PT mean mIoU: {lang_means['pt']:.3f}")
        print(f"  Language effect (EN − PT): {effect:+.3f}")

# Best prompt type (E3)
if e3 is not None:
    pt_means = e3.groupby("prompt_type")["mean_mask_iou"].mean()
    best_pt = pt_means.idxmax()
    print(f"\n  Best prompt type: {best_pt} (mean mIoU = {pt_means[best_pt]:.3f})")
    print(f"  Worst prompt type: {pt_means.idxmin()} "
          f"(mean mIoU = {pt_means.min():.3f})")

# Error source breakdown (E4)
if e4_error is not None:
    count_col = [c for c in e4_error.columns if "count" in c.lower()]
    label_col = [c for c in e4_error.columns if "source" in c.lower() or "type" in c.lower()]
    if count_col and label_col:
        total = e4_error[count_col[0]].sum()
        dominant = e4_error.loc[e4_error[count_col[0]].idxmax()]
        print(f"\n  Dominant error source: {dominant[label_col[0]]} "
              f"({dominant[count_col[0]]}/{total}, "
              f"{dominant[count_col[0]] / total * 100:.1f}%)")

print("\n" + "=" * 60)
